### ISSUE TITLE
Firefox: buttons in header displays with scrollbar

### ISSUE THREAD

**Issue by mpstv** [CyberLight/caninclude-v2#1]
In Firefox header looks like:

![image](https://user-images.githubusercontent.com/54762420/146051849-fb22875a-4ec5-4924-b18f-fbaf6d8c95e0.png)

**Comment by CyberLight** [comment]
Fixed 
<img width="757" alt="image" src="https://user-images.githubusercontent.com/2742061/146684179-dc67ad1d-911e-44ef-8499-2c9bb61eda3f.png">
