### ISSUE TITLE
<details /> tag  accept only <summary/>

### ISSUE THREAD

**Issue by shoonia** [CyberLight/caninclude-v2#3]
Hey! 

I see the the `<details />` tag accept only `<summary/>` and show an error for any else tags.

for example:

`<a/>` -  https://caninclude.glitch.me/caninclude?child=a&parent=details
`<p/>` - https://caninclude.glitch.me/caninclude?child=p&parent=details
`<span/>` - https://caninclude.glitch.me/caninclude?child=span&parent=details
`<div/>` - https://caninclude.glitch.me/caninclude?child=div&parent=details

I guess it's a bug.

**Comment by CyberLight** [comment]
Hi @shoonia ! Thank you for your interest and for your feedback!
This problem has been fixed!
