### ISSUE TITLE
Hi! Please use page to show parent <-> child  [<->] button and the results

### ISSUE THREAD

**Issue by KostiantynO** [CyberLight/caninclude-v2#4]
Hi! Please return back the [<->] button
Because I need to check information for parent <-> child and back child <-> parent from one screen.
I do not want to open 2 different pages for this, this very inconvenient!
Previously it worked one page. Now it requires go back to previous page.

**Comment by CyberLight** [comment]
@KostiantynO thank you for your feedback!
I hope you like my solution.

For desktop:
<img width="718" alt="Screen Shot 2022-01-22 at 21 40 02" src="https://user-images.githubusercontent.com/2742061/150645398-a7e80e93-3247-465b-9ccc-677ad2efb0e1.png">

And mobile:
<img width="305" alt="Screen Shot 2022-01-22 at 21 40 16" src="https://user-images.githubusercontent.com/2742061/150645400-4cc56b3f-f7e1-44b7-ad63-432062f8ae30.png">

**Comment by KostiantynO** [comment]
Yes! Now it looks great 🔥🚀! Works like a charm! Thank you!

Also please kindly check if you can add a simple label to indicate if this tag is parent or child, right beside the "Tag name"
It would be cool!
![image](https://user-images.githubusercontent.com/61573649/151012804-df846950-460a-4c70-8e9d-b4bf9694447b.png)
