### ISSUE TITLE
504 Gateway Time-out on https://caninclude.glitch.me/ 

### ISSUE THREAD

**Issue by grace-snow** [CyberLight/caninclude-v2#5]
Can't find your contact details anywhere to let you know...

![image](https://user-images.githubusercontent.com/10631991/150509298-321702b3-3631-4219-a317-1f509a6aa33e.png)

This site is great, and lots of people I know are using it now. **We'd love it if you could restore service please.** 

Thanks

----
p.s. Ever looking for contributors on this? Could be a good open source project

**Comment by CyberLight** [comment]
@grace-snow thank you so much! Unfortunately, I found that there were problems on the side of glitch.com.
